In [1]:
import pandas as pd

In [2]:
sdp = 'school-distinctive-programmes.csv'
cca = 'co-curricular-activities-ccas.csv'
mp = 'moe-programmes.csv'
so = 'subjects-offered.csv'

In [3]:
sdp_df = pd.read_csv(sdp, encoding="ISO-8859-1")
cca_df = pd.read_csv(cca, encoding="ISO-8859-1")
mp_df = pd.read_csv(mp, encoding="ISO-8859-1")
so_df = pd.read_csv(so, encoding="ISO-8859-1")

In [4]:
list(sdp_df)

['school_name',
 'alp_domain',
 'alp_title',
 'llp_domain1',
 'llp_title1',
 'llp_domain2',
 'llp_title2']

In [5]:
list(cca_df)

['school_name',
 'school_section',
 'cca_grouping_desc',
 'cca_generic_name',
 'cca_customized_name']

In [6]:
list(mp_df)

['school_name', 'moe_programme_desc']

In [7]:
list(so_df)

['school_name', 'subject_desc']

In [8]:
cca_df["school_name"].value_counts()

HWA CHONG INSTITUTION                         68
RAFFLES INSTITUTION                           60
VICTORIA JUNIOR COLLEGE                       55
RIVER VALLEY HIGH SCHOOL                      46
NUS HIGH SCHOOL OF MATHEMATICS AND SCIENCE    45
                                              ..
PUNGGOL VIEW PRIMARY SCHOOL                    7
KHENG CHENG SCHOOL                             7
ST. PATRICK'S SCHOOL                           4
ELIAS PARK PRIMARY SCHOOL                      4
QIHUA PRIMARY SCHOOL                           1
Name: school_name, Length: 325, dtype: int64

In [9]:
cca_df.head()

,school_name,school_section,cca_grouping_desc,cca_generic_name,cca_customized_name
0,ADMIRALTY PRIMARY SCHOOL,PRIMARY,PHYSICAL SPORTS,MODULAR CCA (SPORTS),SPORTS CLUB
1,ADMIRALTY PRIMARY SCHOOL,PRIMARY,VISUAL AND PERFORMING ARTS,ART AND CRAFTS,VISUAL ARTS CLUB
2,ADMIRALTY PRIMARY SCHOOL,PRIMARY,CLUBS AND SOCIETIES,"ENGLISH LANGUAGE, DRAMA AND DEBATING",ENGLISH LANGUAGE AND DRAMA
3,ADMIRALTY PRIMARY SCHOOL,PRIMARY,CLUBS AND SOCIETIES,INFOCOMM TECHNOLOGY (COMPUTING),INFOCOMM TECHNOLOGY
4,ADMIRALTY PRIMARY SCHOOL,PRIMARY,CLUBS AND SOCIETIES,DESIGN AND INNOVATION,na

In [10]:
main_df = sdp_df.merge(cca_df, how='outer', on='school_name')

In [11]:
main_df.head()

,school_name,alp_domain,alp_title,llp_domain1,llp_title1,llp_domain2,llp_title2,school_section,cca_grouping_desc,cca_generic_name,cca_customized_name
0,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,PHYSICAL SPORTS,MODULAR CCA (SPORTS),SPORTS CLUB
1,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,VISUAL AND PERFORMING ARTS,ART AND CRAFTS,VISUAL ARTS CLUB
2,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,CLUBS AND SOCIETIES,"ENGLISH LANGUAGE, DRAMA AND DEBATING",ENGLISH LANGUAGE AND DRAMA
3,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,CLUBS AND SOCIETIES,INFOCOMM TECHNOLOGY (COMPUTING),INFOCOMM TECHNOLOGY
4,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,CLUBS AND SOCIETIES,DESIGN AND INNOVATION,na

In [12]:
merge_two = main_df.merge(mp_df, how='outer', on='school_name')

In [13]:
merge_two

,school_name,alp_domain,alp_title,llp_domain1,llp_title1,llp_domain2,llp_title2,school_section,cca_grouping_desc,cca_generic_name,cca_customized_name,moe_programme_desc
0,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,PHYSICAL SPORTS,MODULAR CCA (SPORTS),SPORTS CLUB,NaN
1,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,VISUAL AND PERFORMING ARTS,ART AND CRAFTS,VISUAL ARTS CLUB,NaN
2,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,CLUBS AND SOCIETIES,"ENGLISH LANGUAGE, DRAMA AND DEBATING",ENGLISH LANGUAGE AND DRAMA,NaN
3,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,CLUBS AND SOCIETIES,INFOCOMM TECHNOLOGY (COMPUTING),INFOCOMM TECHNOLOGY,NaN
4,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,CLUBS AND SOCIETIES,DESIGN AND INNOVATION,na,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
6300,DUNMAN HIGH SCHOOL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MUSIC ELECTIVE PROGRAMME
6301,DUNMAN HIGH SCHOOL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BICULTURAL STUDIES PROGRAMME
6302,NAN HUA HIGH SCHOOL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LANGUAGE ELECTIVE PROGRAMME (CHINESE)
6303,NANYANG JUNIOR COLLEGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ART ELECTIVE PROGRAMME
6304,NANYANG JUNIOR COLLEGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LANGUAGE ELECTIVE PROGRAMME (CHINESE)

In [14]:
final_df = merge_two.merge(so_df, how='outer', on='school_name')

In [15]:
final_df

,school_name,alp_domain,alp_title,llp_domain1,llp_title1,llp_domain2,llp_title2,school_section,cca_grouping_desc,cca_generic_name,cca_customized_name,moe_programme_desc,subject_desc
0,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,PHYSICAL SPORTS,MODULAR CCA (SPORTS),SPORTS CLUB,NaN,ART
1,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,PHYSICAL SPORTS,MODULAR CCA (SPORTS),SPORTS CLUB,NaN,CHINESE
2,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,PHYSICAL SPORTS,MODULAR CCA (SPORTS),SPORTS CLUB,NaN,ENGLISH LANGUAGE
3,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,PHYSICAL SPORTS,MODULAR CCA (SPORTS),SPORTS CLUB,NaN,FOUNDATION CHINESE
4,ADMIRALTY PRIMARY SCHOOL,STEM,Design Thinking for Sustainability (DTS @ Admi...,Community Service & Student Leadership,High Performance Mind-set for Personal Leadership,NaN,NaN,PRIMARY,PHYSICAL SPORTS,MODULAR CCA (SPORTS),SPORTS CLUB,NaN,HIGHER CHINESE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56307,NANYANG JUNIOR COLLEGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LANGUAGE ELECTIVE PROGRAMME (CHINESE),H3 ECONOMICS
56308,NANYANG JUNIOR COLLEGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LANGUAGE ELECTIVE PROGRAMME (CHINESE),H3 HISTORY
56309,NANYANG JUNIOR COLLEGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LANGUAGE ELECTIVE PROGRAMME (CHINESE),H3 PHYSICS
56310,NANYANG JUNIOR COLLEGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LANGUAGE ELECTIVE PROGRAMME (CHINESE),NTU MOLECULAR BIOLOGY
56311,NANYANG JUNIOR COLLEGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LANGUAGE ELECTIVE PROGRAMME (CHINESE),NTU SEMICONDUCTOR PHYSICS & DEVICES

In [16]:
stem_df = final_df.loc[final_df["alp_domain"] == "STEM"]

In [17]:
stem_df.count()

school_name            4979
alp_domain             4979
alp_title              4979
llp_domain1            4979
llp_title1             4979
llp_domain2               0
llp_title2                0
school_section         4977
cca_grouping_desc      4977
cca_generic_name       4977
cca_customized_name    4977
moe_programme_desc      310
subject_desc           4960
dtype: int64

In [18]:
stem_df_clean = stem_df.drop(["llp_domain2", "llp_title2"], axis=1)

In [19]:
stem_df_clean.count()

school_name            4979
alp_domain             4979
alp_title              4979
llp_domain1            4979
llp_title1             4979
school_section         4977
cca_grouping_desc      4977
cca_generic_name       4977
cca_customized_name    4977
moe_programme_desc      310
subject_desc           4960
dtype: int64